name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --windowed --name "SOSH_Kanta_validointityokalu" GUI_validator.py

    - name: List dist directory contents
      run: dir dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SOSH Kanta Validointityokalu
        path: dist/SOSH_Kanta_validointityokalu.exe
        if-no-files-found: warn
